### ISSUE TITLE
Create a logo for the project

### ISSUE THREAD

**Issue by tribakzero** [tribakzero/decor-pikmin-finder#6]
An idea is a Huge seedling shape with a Question Mark sign and colored in gray or gold.
Integrate the logo to the page and repo.

**Comment by tribakzero** [comment]
Current draft/proposal:

![Group 1](https://user-images.githubusercontent.com/6462719/149885436-6d58a972-55f3-4e8d-a106-a1ffcbd5e867.png)

**Comment by vnponce** [comment]
LGTM 🍕 🌮

**Comment by tribakzero** [comment]
How it looks inside the project:
<img width="1440" alt="Screen Shot 2022-01-19 at 21 43 48" src="https://user-images.githubusercontent.com/6462719/150269542-92559808-d255-4806-a6b4-351dea392021.png">

Still pending to add it to favicons and other metaimages, but will leave it as is for the moment.
